name: Docker build and push to Artifact Registry

on:
  pull_request:
    branches:
      - deployment

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: "webservice"
            image: "ml-service"
          - context: "evidently_service"
            image: "evidently_service"
          - context: "prometheus"
            image: "prometheus"
          - context: "grafana"
            image: "grafana"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        token_format: access_token

    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.context }}
        push: true
        tags: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.DOCKER_REPOSITORY }}/${{ matrix.image }}:latest
        no-cache: true
        platforms: linux/amd64